### ISSUE TITLE
Repeated plays during builder.yml run

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/kube-ansible#145]
Apparently there's a duplicated play running while using the builder playbook.

This play is running twice, apparently once after the `auto-kube-dev/roles/verify-environment`, and then again after `install-docker`:

```
TASK [auto-kube-dev/roles/install-deps-utils : Install deps and utils]
```

It's likely not causing a big impact, but, not exactly clean.

[Pastebin from Leif](https://pastebin.com/cvLQQPAF)

### Steps to reproduce

Using these extra vars:

```
---
bridge_networking: true
skip_virthost_depedencies: true
perform_hardware_checks: false
virtual_machines:
  - name: builder
    node_type: builder
    system_ram_mb: 24576
```

Spin up a VM

```
 ansible-playbook -i inventory/doug/vms.inventory -e "@./inventory/builder-extravars.yml" virthost-setup.yml 
```

Then run the builder:

```
ansible-playbook -i inventory/vms.local.generated -e "@./inventory/builder-extravars.yml" builder.yml
```
