### ISSUE TITLE
[networking] flannel doesn't start properly when using `control_plane_listen_all=true`

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/kube-ansible#180]
Following from comments I made on IRC so I don't have to redo it :)

If you use my new option `control_plane_listen_all=true` it will set the configuration in the [MasterConfiguration](https://github.com/redhat-nfvpe/kube-ansible/blob/master/roles/kube-init/files/kubeadm_control_plane_listen_all.cfg) (like what happens with ipv6 to instantiate the proper addresses during kubeadm spin up), which basically sets the listen address for the scheduler container and the controller container (in the kube-system namespace) to `--listen 0.0.0.0` instead of the default of `--listen
127.0.0.1`.

If you enable just that one option (using NAT networking; maybe it works differently with bridged networking?), then the flannel containers won't complete their configuration correctly (they start and run fine, but the logs show that CNI isn't up), so the 224.x.x.x network doesn't come up, which then results in kube-dns not starting up.

I reason I'm changing the listen address is that it's necessary for [prometheus-operator prerequisites](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#prerequisites) so that it can be in the `monitoring` namespace and connect to the interfaces of the scheduler and controller containers so that they are monitored from Prometheus.

I've made everything work in minikube, but it doesn't use flannel for networking like we do (by default) in kube-ansible, and I've mostly run out of ideas on where to look at debugging next.

I'm instantiating my setup like this:

```
ansible-playbook -i inventory/virthost virthost-setup.yml ; ansible-playbook -i inventory/vms.local.generated -e "control_plane_listen_all=true" kube-install.yml
```

So it should be pretty straight forward. Use your existing `virthost` setup, and deploy the same as normal, but add the `-e "control_plane_listen_all=true"` in order to replicate.

I'm spinning it up again right now, and I'll provide the logs in some comments momentarily.

**Comment by leifmadsen** [comment]
CC: @dougbtv @s1061123

**Comment by leifmadsen** [comment]
```
[centos@kube-master ~]$ kubectl get all -n kube-system
NAME                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
ds/kube-flannel-ds   4         4         4         4            4           beta.kubernetes.io/arch=amd64   53m
ds/kube-proxy        4         4         4         4            4           <none>                          53m

NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns   1         1         1            0           53m

NAME                    DESIRED   CURRENT   READY     AGE
rs/kube-dns-6f4fd4bdf   1         1         0         53m

NAME                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
ds/kube-flannel-ds   4         4         4         4            4           beta.kubernetes.io/arch=amd64   53m
ds/kube-proxy        4         4         4         4            4           <none>                          53m

NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns   1         1         1            0           53m

NAME                    DESIRED   CURRENT   READY     AGE
rs/kube-dns-6f4fd4bdf   1         1         0         53m

NAME                                     READY     STATUS              RESTARTS   AGE
po/etcd-kube-master                      1/1       Running             0          52m
po/kube-apiserver-kube-master            1/1       Running             0          52m
po/kube-controller-manager-kube-master   1/1       Running             0          52m
po/kube-dns-6f4fd4bdf-vt2fr              0/3       ContainerCreating   0          53m
po/kube-flannel-ds-2gnct                 2/2       Running             1          53m
po/kube-flannel-ds-7knqn                 2/2       Running             0          53m
po/kube-flannel-ds-flst4                 2/2       Running             0          53m
po/kube-flannel-ds-qtndr                 2/2       Running             0          53m
po/kube-proxy-chc6p                      1/1       Running             0          53m
po/kube-proxy-m829r                      1/1       Running             0          53m
po/kube-proxy-mmqtd                      1/1       Running             0          53m
po/kube-proxy-rs25w                      1/1       Running             0          53m
po/kube-scheduler-kube-master            1/1       Running             0          52m

NAME           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
svc/kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP   53m
```

**Comment by leifmadsen** [comment]
```
[centos@kube-master ~]$ kubectl logs -n kube-system po/kube-flannel-ds-2gnct kube-flannel
I0219 14:44:37.237278       1 kube.go:109] Waiting 10m0s for node controller to sync
I0219 14:44:37.237492       1 kube.go:289] starting kube subnet manager
I0219 14:44:38.237644       1 kube.go:116] Node controller sync successful
I0219 14:44:38.237696       1 main.go:132] Installing signal handlers
I0219 14:44:38.237801       1 manager.go:136] Determining IP address of default interface
I0219 14:44:38.238017       1 manager.go:149] Using interface with name eth0 and address 192.168.122.87
I0219 14:44:38.238032       1 manager.go:166] Defaulting external address to interface address (192.168.122.87)
E0219 14:44:38.250514       1 network.go:102] failed to register network: failed to acquire lease: node "kube-node-2" pod cidr not assigned
E0219 14:44:39.250921       1 network.go:102] failed to register network: failed to acquire lease: node "kube-node-2" pod cidr not assigned
E0219 14:44:40.251213       1 network.go:102] failed to register network: failed to acquire lease: node "kube-node-2" pod cidr not assigned
...[repeating]...
```

**Comment by leifmadsen** [comment]
```
[centos@kube-master ~]$ kubectl get nodes -o wide
NAME          STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION          CONTAINER-RUNTIME
kube-master   Ready     master    56m       v1.9.3    <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.12.6
kube-node-1   Ready     <none>    55m       v1.9.3    <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.12.6
kube-node-2   Ready     <none>    55m       v1.9.3    <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.12.6
kube-node-3   Ready     <none>    55m       v1.9.3    <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.12.6
```

**Comment by leifmadsen** [comment]
```
[centos@kube-master ~]$ kubectl describe -n kube-system po/kube-controller-manager-kube-master
Name:         kube-controller-manager-kube-master
Namespace:    kube-system
Node:         kube-master/192.168.122.153
Start Time:   Mon, 19 Feb 2018 14:42:33 +0000
Labels:       component=kube-controller-manager
              tier=control-plane
Annotations:  kubernetes.io/config.hash=ff9c8ebaa9b0e26e1d23281a7e56483f
              kubernetes.io/config.mirror=ff9c8ebaa9b0e26e1d23281a7e56483f
              kubernetes.io/config.seen=2018-02-19T14:42:28.616740109Z
              kubernetes.io/config.source=file
              scheduler.alpha.kubernetes.io/critical-pod=
Status:       Running
IP:           192.168.122.153
Containers:
  kube-controller-manager:
    Container ID:  docker://f2cb1a49f9b7a91bee8ff996385eee4985e86cb3a8e5f438048adc9037b9487a
    Image:         gcr.io/google_containers/kube-controller-manager-amd64:v1.9.3
    Image ID:      docker-pullable://gcr.io/google_containers/kube-controller-manager-amd64@sha256:3ac295ae3e78af5c9f88164ae95097c2d7af03caddf067cb35599769d0b7251e
    Port:          <none>
    Command:
      kube-controller-manager
      --address=0.0.0.0
      --leader-elect=true
      --use-service-account-credentials=true
      --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
      --controllers=*,bootstrapsigner,tokencleaner
      --kubeconfig=/etc/kubernetes/controller-manager.conf
      --root-ca-file=/etc/kubernetes/pki/ca.crt
      --service-account-private-key-file=/etc/kubernetes/pki/sa.key
      --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    State:          Running
      Started:      Mon, 19 Feb 2018 14:42:55 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        200m
    Liveness:     http-get http://0.0.0.0:10252/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/kubernetes/controller-manager.conf from kubeconfig (ro)
      /etc/kubernetes/pki from k8s-certs (ro)
      /etc/pki from ca-certs-etc-pki (ro)
      /etc/ssl/certs from ca-certs (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  ca-certs-etc-pki:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/pki
    HostPathType:  DirectoryOrCreate
  k8s-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/pki
    HostPathType:  DirectoryOrCreate
  ca-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  kubeconfig:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/controller-manager.conf
    HostPathType:  FileOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:            <none>
```

---

```
[centos@kube-master ~]$ kubectl describe -n kube-system po/kube-scheduler-kube-master
Name:         kube-scheduler-kube-master
Namespace:    kube-system
Node:         kube-master/192.168.122.153
Start Time:   Mon, 19 Feb 2018 14:42:33 +0000
Labels:       component=kube-scheduler
              tier=control-plane
Annotations:  kubernetes.io/config.hash=5aaf7746108646d9dbe8e9269cc9f91b
              kubernetes.io/config.mirror=5aaf7746108646d9dbe8e9269cc9f91b
              kubernetes.io/config.seen=2018-02-19T14:42:28.61673272Z
              kubernetes.io/config.source=file
              scheduler.alpha.kubernetes.io/critical-pod=
Status:       Running
IP:           192.168.122.153
Containers:
  kube-scheduler:
    Container ID:  docker://1170a1878197a634fa8c1294817094159a434b9fadac3f073816d025c4246455
    Image:         gcr.io/google_containers/kube-scheduler-amd64:v1.9.3
    Image ID:      docker-pullable://gcr.io/google_containers/kube-scheduler-amd64@sha256:2c17e637c8e4f9202300bd5fc26bc98a7099f49559ca0a8921cf692ffd4a1675
    Port:          <none>
    Command:
      kube-scheduler
      --address=0.0.0.0
      --kubeconfig=/etc/kubernetes/scheduler.conf
      --leader-elect=true
    State:          Running
      Started:      Mon, 19 Feb 2018 14:43:07 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Liveness:     http-get http://0.0.0.0:10251/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/kubernetes/scheduler.conf from kubeconfig (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  kubeconfig:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/scheduler.conf
    HostPathType:  FileOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:            <none>
```

**Comment by leifmadsen** [comment]
```
[centos@kube-master ~]$ ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:88:d3:59 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.153/24 brd 192.168.122.255 scope global dynamic eth0
       valid_lft 2603sec preferred_lft 2603sec
    inet6 fe80::5054:ff:fe88:d359/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:a0:fd:82:57 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN 
    link/ether 6e:bc:1d:2a:cc:f3 brd ff:ff:ff:ff:ff:ff
```

```
[centos@kube-master ~]$ ip route show
default via 192.168.122.1 dev eth0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.122.0/24 dev eth0  proto kernel  scope link  src 192.168.122.153 
```

**Comment by leifmadsen** [comment]
```
[root@kube-master ~]# kubeadm config view
api:
  advertiseAddress: 192.168.122.153
  bindPort: 6443
authorizationModes:
- Node
- RBAC
certificatesDir: /etc/kubernetes/pki
cloudProvider: ""
controllerManagerExtraArgs:
  address: 0.0.0.0
etcd:
  caFile: ""
  certFile: ""
  dataDir: /var/lib/etcd
  endpoints: null
  image: ""
  keyFile: ""
imageRepository: gcr.io/google_containers
kubeProxy:
  config:
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    clusterCIDR: ""
    configSyncPeriod: 15m0s
    conntrack:
      max: null
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    featureGates: ""
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      minSyncPeriod: 0s
      scheduler: ""
      syncPeriod: 30s
    metricsBindAddress: 127.0.0.1:10249
    mode: ""
    oomScoreAdj: -999
    portRange: ""
    resourceContainer: /kube-proxy
    udpTimeoutMilliseconds: 250ms
kubeletConfiguration: {}
kubernetesVersion: v1.9.3
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
nodeName: kube-master
schedulerExtraArgs:
  address: 0.0.0.0
token: ""
tokenTTL: 24h0m0s
unifiedControlPlaneImage: ""
```
