### ISSUE TITLE
kube-ansible build hangs with master branch

### ISSUE THREAD

**Issue by verizonold** [redhat-nfvpe/kube-ansible#227]
Hi,
Compiling with the master branch and kube-ansible build hangs as follows:

```
TASK [multus-cni : Copy compiled cni binaries] *********************************
changed: [kubemaster] => (item=/usr/src/cni-plugins/bin/*)
changed: [kubeminion1] => (item=/usr/src/cni-plugins/bin/*)
changed: [kubeminion2] => (item=/usr/src/cni-plugins/bin/*)
changed: [kubeminion1] => (item=/usr/src/sriov-cni/bin/*)
changed: [kubemaster] => (item=/usr/src/sriov-cni/bin/*)
changed: [kubeminion2] => (item=/usr/src/sriov-cni/bin/*)
changed: [kubemaster] => (item=/usr/src/multus-cni/bin/*)
changed: [kubeminion1] => (item=/usr/src/multus-cni/bin/*)
changed: [kubeminion2] => (item=/usr/src/multus-cni/bin/*)

RUNNING HANDLER [kokonet-setup : shut down eth1] *******************************

RUNNING HANDLER [kokonet-setup : pause] ****************************************

RUNNING HANDLER [kokonet-setup : bring up eth1] ********************************

RUNNING HANDLER [npwg-poc1-setup : shut down eth1] *****************************
```

Any causes for the above hanging?

**Comment by s1061123** [comment]
I may fixed just before, so could you please do 'git pull' and try it again?

If you can see same failure, could you please share all argument of ansible-playbook?

**Comment by s1061123** [comment]
Now I am adding additional fix. Let you know when I'm done.

**Comment by s1061123** [comment]
@verizonold , I commit candidate fix. Could you please try it with latest?

If you can see same failure, could you please share output with 'ansible-playbook -vvv' because we would like to know your condition?

**Comment by dougbtv** [comment]
Thanks Tomo for addressing quickly. I tried to replicate it as well using master HEAD, and I had a successful run (that is, I wasn't able to replicate it, so it may have been fixed in the latest changes).

For what it's worth I'm using extra vars that look like this:

```
---
crd_namespace: "kubernetes.cni.cncf.io"
multus_use_default_network: true
multus_version: "dev/network-plumbing-working-group-crd-change"
network_type: "npwg-poc1"
multus_git_url: "https://github.com/Intel-Corp/multus-cni.git"
bridge_networking: true
bridge_name: br0
bridge_physical_nic: "enp1s0f1"
bridge_network_name: "br0"
bridge_network_cidr: 192.168.1.0/24
pod_network_type: "multus"
virtual_machines:
  - name: kube-multustest-master
    node_type: master
  - name: kube-multustest-node-1
    node_type: nodes
multus_use_crd: true
multus_ipam_subnet: "192.168.1.0/24"
multus_ipam_rangeStart: "192.168.1.200"
multus_ipam_rangeEnd: "192.168.1.216"
multus_ipam_gateway: "192.168.1.1"
```

And I'm running the playbooks like:

```
$ ansible-playbook -i inventory/virthost.inventory -e "@./inventory/examples/npwg-poc/poc-extravars.yml" playbooks/vm-teardown.yml && ansible-playbook -i inventory/virthost.inventory -e "@./inventory/examples/npwg-poc/poc-extravars.yml" playbooks/virthost-setup.yml && ansible-playbook -i inventory/vms.local.generated -e "@./inventory/examples/npwg-poc/poc-extravars.yml" playbooks/kube-install.yml
```
