### ISSUE TITLE
Allow virtual machines to be parameterized

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/kube-ansible#99]
When building a `virtual_machines` list, we should be able to parameterize the list so that you can specify requirements for the VMs, like RAM, CPU, etc independently. This will be required for the build environment work.

**Comment by leifmadsen** [comment]
Should be pretty straight forward now that feature/ipv6 is merged. Will start working on building this out as I'll need it for a development box. We don't want *all* our VMs to be provisioned with 24GB of RAM :)

**Comment by leifmadsen** [comment]
@dougbtv @fepan @s1061123, so I have a design question about what I want to do here.

We currently have this:

```
virtual_machines:                                                               
  - name: kube-master                                                           
    node_type: master                                                              
  - name: kube-node-1                                                                                                                                                                                                                          
    node_type: nodes                                                               
  - name: kube-node-2                                                              
    node_type: nodes                                                               
  - name: kube-node-3                                                              
    node_type: nodes                                                               
# - name: my-support-node                                                          
#   node_type: other                                                               
vm_parameters_ram_mb: 2048                                                         
vm_parameters_cpus: 4      
```

What I want to do is move the values of the `vm_parameters_...` to be available to the `virtual_machines` so that I can specify different RAM and CPU values for the machines.

I was just thinking of doing something like this:

```
virtual_machines:
  - name: kube-master
    node_type: master
    vm_parameters_ram_mb: 2048
    vm_parameters_cpus: 4
```

But then I was thinking, that maybe we'll just keep adding more and more things here... so maybe we should have a `parameters` dictionary?

```
virtual_machines:
  - name: kube-master
    node_type: master
    parameters:
        ram_mb: 2048
        cpus: 4
```

I'd also want to set a default, so I'd be replacing `vm_parameters_...` with something like:

`default_parameter_ram_mb: 2048`

Then if the individual dictionaries were missing, then I'd just consume the default values. Thoughts?
